#!/bin/bash

ai_mr () {
  echo "Moving to: $1"
  cd $1 
  git checkout master
  git pull
  echo "Repository is up to date"
  echo "Checking out branch: $2"
  echo Review or explain:$3
  git checkout $2
  
  command="ollama.exe run deepseek-coder:6.7b"
  echo "Using DeepSeek Coder's 6.7b model for code review."
  #echo $(git branch --show)
  echo $(git rev-parse --abbrev-ref HEAD)
  echo $pwd
  if [ "$3" = "review" ]; then
    echo "Reviewing MR for branch $2"
  elif [ "$3" = "explain" ]; then
    echo "Explaining MR for branch $2"
  fi
  diff=$(git diff master)
  if [ "$3" = "explain" ]; then
    echo "PR diff: $diff. Suppose you wrote the code in the git PR diff above. Provide a brief summary of this PR, ignore any files that are not critical to the code, i.e: package-json.lock, and state the changes you made to existing code in markdown format, and in first person."| $command
  elif [ "$3" = "review" ]; then
    echo "Review this code: $diff, provide suggestions for improvement, coding best practices, improve readability, and maintainability. Remove any code smells and anti-patterns. Provide code examples for your suggestion. Respond in markdown format. If the file does not have any code or does not need any changes, say 'No changes needed'."| $command
  fi
}

ai_mr "$@"